### Create
POST http://localhost:3000/api/wilder HTTP/1.1
content-type: application/json

{
    "name": "sofiane",
    "city": "allemagn",
    "skills": [
        { "title": "express", "vote": 5 },
        { "title": "mongo", "vote": 5 }
    ]
}


### Read
GET http://localhost:3000/api/wilder HTTP/1.1


### Update
PUT http://localhost:3000/api/wilder HTTP/1.1
content-type: application/json

{
    "_id": "6142fea70832e911cc99f973",
    "name": "wcs",
    "city": "allem",
    "skills": [
        { "title": "express", "vote": 5 },
        { "title": "mongo", "vote": 5 }
    ]
}


### DELETE
DELETE http://localhost:3000/api/wilder HTTP/1.1
content-type: application/json

{
    "_id": "6141fca61d708a70b8100e51"
}




